name: Build and Push Docker Image

run-name: Build and push llama-stack image to quay.io

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        uses: ./.github/actions/setup-runner

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Safety check
        if: github.repository_owner == 'trustyai-explainability'
        run: echo "Repository owner is trusted."

      - name: Log in to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_SECRET }}

      - name: Build and push Docker image
        run: |
          # Build the trustyai distribution using llama stack build
          USE_COPY_NOT_MOUNT=true LLAMA_STACK_DIR=. uv run llama stack build \
            --config trustyai-distribution/build.yaml \
            --image-type container \
            --image-name llama-stack-trustyai
          
          # Tag the built image with the full registry path
          docker tag llama-stack-trustyai:dev quay.io/trustyai/llama-stack:latest
          
          # Also tag with commit SHA for versioning
          docker tag quay.io/trustyai/llama-stack:latest quay.io/trustyai/llama-stack:${{ github.sha }}
          
          # Push both images
          docker push quay.io/trustyai/llama-stack:latest
          docker push quay.io/trustyai/llama-stack:${{ github.sha }}

      - name: Verify image
        run: |
          # Test that the image can start
          docker run --rm quay.io/trustyai/llama-stack:latest python -c "import llama_stack; print('Image verification successful')"
          
          # Test that the server can start (basic functionality check)
          timeout 30s docker run --rm quay.io/trustyai/llama-stack:latest python -m llama_stack.distribution.server.server --help || true 